version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: pokemon_tournament_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd1
      POSTGRES_DB: tournament
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/resources/sql/bd.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: